Header_links:
  type: list
  default: "YouTube,fab-youtube,https://www.youtube.com/channel/UCE64wWpZ9FebjnpZ8ndcW-Q?sub_confirmation=1,vdm,blank"
  description:
    en: "Comma delimited in this order: Title,Icon,URL,View,Target. View can be:  visible on both desktop and mobile devices (vdm), Desktop only (vdo) or mobile only (vmo). Target can be: same tab (self) or new tab (blank)."
Svg_icons:
  type: "list"
  list_type: "compact"
  default: "fab-facebook|fab-twitter|temperature-low"
  description:
    en: "Include FontAwesome 5 icon classes for each icon used in the list."
